[package]
name = "drc-vnc"
version = "0.1.0"
edition = "2024"

[dependencies]
drc = { version = "0.1.0", path = "../drc" }
image = "0.25.9"
snafu = "0.8.9"
tokio = { version = "1.48.0", features = ["full"] }
vnc-rs = "0.5.2"
x264 = { version = "0.5.0", path = "../x264" }
yuv = "0.8.9"
