[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
strawberry = { version = "0.1.0", path = "../strawberry" }
ffmpeg-next = "8.0.0"
snafu = "0.8.9"
tokio = "1.48.0"
strawberry-x264 = { version = "0.1.0", path = "../strawberry-x264" }
